[tool.poetry]
name = "pyportable-crypto"
version = "1.3.0a15"
homepage = "https://github.com/likianta/pyportable-crypto"
description = "Crypto plugin for pyportable-installer project."
authors = ["Likianta <likianta@foxmail.com>"]
packages = [{ include = "pyportable_crypto" }]
exclude = ["pyportable_crypto/cipher_gen/_cache/*/"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
argsense = "^0.5.8"
cython = "*"
# lk-logger = "^5.6.4"
lk-logger = { version = "^6.0.0a1", source = "likianta-host" }
# lk-utils = "^2.10.0"
lk-utils = { version = "^2.10.8", source = "likianta-host" }
setuptools = "^70.0.0"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2006/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
