[tool.poetry]
name = "pyportable-crypto"
version = "1.2.1a5"
homepage = "https://github.com/likianta/pyportable-crypto"
description = "Crypto plugin for pyportable-installer project."
authors = ["Likianta <likianta@foxmail.com>"]
packages = [{ include = "pyportable_crypto" }]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
argsense = "^0.5.7"
cython = "*"
lk-logger = "^5.6.4"
lk-utils = "^2.10.0"
setuptools = "^70.0.0"

# [tool.poetry.group.dev.dependencies]
# cython = "*"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2006/"
priority = "supplemental"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
