[tool.poetry]
name = "pyportable-crypto"
version = "1.1.0b3"
homepage = "https://github.com/likianta/pyportable-crypto"
description = "Crypto plugin for pyportable-installer project."
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
lk-logger = "^5.6.1"
lk-utils = "^2.5.6"
argsense = { version = "^0.5.2", optional = true }

[tool.poetry.extras]
cli = ["argsense"]

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
