[tool.poetry]
name = "pyportable-crypto"
version = "1.1.1a0"
homepage = "https://github.com/likianta/pyportable-crypto"
description = "Crypto plugin for pyportable-installer project."
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
argsense = "^0.5.2"
lk-logger = "^5.6.2"
lk-utils = "^2.5.6"

[tool.poetry.group.dev.dependencies]
cython = "*"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "default"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
