import os
import secrets

SALT = os.getenv(
    'PYPORTABLE_CRYPTO_SALT',
    '1c0aad9ecb73b2e837a1ac10938e715db27484bfed6515e8140d5d02191804facdc266c704'
    #   the fallback salt value is randomly generated by 
    #   `secrets.token_hex(37)` (74 chars in total).
    #   i would update it periodically (usually every month or every formal
    #   version release).
    #   note that the salt is not secret. it is fine if an attacker knows it.
    #   ref: https://chatgpt.com/share/6a44b1ce-ffb0-83ee-93d8-dbf7e52a9663
)


def add_salt(key: str, salt: str = SALT) -> str:
    """
    add salt to the key.
    """
    assert 0 < len(key) <= len(salt)
    return ''.join(f'{k}{s}' for k, s in zip(key, salt))


def generate_random_key(bytelen: int = 32) -> str:
    assert bytelen % 2 == 0
    return secrets.token_hex(int(bytelen / 2))


def generate_random_bytes(n: int = 32) -> bytes:
    return secrets.SystemRandom().randbytes(n)
