import os
import secrets

SALT = os.getenv(
    'PYPORTABLE_CRYPTO_SALT',
    '697a992260612ef38c16d76bac3c3e1c5482187c336cd9b9e7d8945aad783c2c1569aefd7f'
    #   the fallback salt value is randomly generated by 
    #   `secrets.token_hex(37)` (74 chars in total).
    #   i would update it periodically (usually every month or every formal
    #   version release).
    #   note that the salt is not secret. it is fine if an attacker knows it.
    #   ref: https://chatgpt.com/share/6a44b1ce-ffb0-83ee-93d8-dbf7e52a9663
)


def add_salt(key: str, salt: str = SALT) -> str:
    """
    add salt to the key.
    """
    assert 0 < len(key) <= len(salt)
    return ''.join(f'{k}{s}' for k, s in zip(key, salt))


def random_key(bytelen: int = 32) -> str:
    assert bytelen % 2 == 0
    return secrets.token_hex(int(bytelen / 2))


def random_bytes(n: int = 32) -> bytes:
    return secrets.SystemRandom().randbytes(n)
