import os
import secrets

SALT = os.getenv(
    'PYPORTABLE_CRYPTO_SALT',
    '8f76d8d45980cb7fa4a242a7791bc7b0ac1fce03dc221acd308b922c51245d5443e3eedcc3'
    'ecfb0788ce3478c57e6bfdb1d0139cc9ef42a608d44d03ecf5bb771c410d762261fedaf43c'
    '8019d0831c21688dfaf9e007fc2dab45b24e752fdf285db6c655',
    #   the fallback salt value is randomly generated by 
    #   `secrets.token_hex(100)`.
    #   i would update it periodically (usually every month or every formal
    #   version release).
    #   note that the salt is not secret. it is fine if an attacker knows it.
    #   ref: https://chatgpt.com/share/6a44b1ce-ffb0-83ee-93d8-dbf7e52a9663
)


def add_salt(key: str, salt: str = SALT) -> str:
    """
    add salt to the key.
    """
    assert 0 < len(key) <= len(salt)
    return ''.join(f'{k}{s}' for k, s in zip(key, salt))


def generate_random_key(bytelen: int = 32) -> str:
    assert bytelen % 2 == 0
    return secrets.token_hex(int(bytelen / 2))


def generate_random_bytes(n: int = 32) -> bytes:
    return secrets.SystemRandom().randbytes(n)
